### PR TITLE
add a default image for a product if no image url given

### PR DESCRIPTION
**Pull request by shreyassp17**
Added placeholder.png image in public foler as the default image to be displayed if no specific image url is given while creating a new product.

bugfix

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks shreyassp17, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Some issues need to be fixed before you can merge your PR:
 - Looks like you run npm install, but we're using yarn. Please remove "frontend/package-lock.json" from your PR and use yarn instead.

**Review by vanessa-cooper — DISMISSED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by ghost — APPROVED** [review]
Excellent job shreyassp17! You're now able to merge the PR.

**Pull request merged**
